#!/bin/bash

#[[ $- == *i* ]] || return 0

# http://www.commandlinefu.com/commands/view/5423/view-all-date-formats-quick-reference-help-alias
alias dateh='date --help|sed "/^ *%a/,/^ *%Z/!d;y/_/!/;s/^ *%\([:a-z]\+\) \+/\1_/gI;s/%/#/g;s/^\([a-y]\|[z:]\+\)_/%%\1_%\1_/I"|while read L;do date "+${L}"|sed y/!#/%%/;done|column -ts_'
