#!/bin/bash

# History environment variables belong in rc because they are only useful when
# in interactive mode.
#[[ $- == *i* ]] || return 0

HISTCONTROL="erasedups:ignoreboth"
HISTFILESIZE=100000
HISTSIZE=500000
HISTTIMEFORMAT='%F %T '

# Don't record commands that match these patterns in the history file
HISTIGNORE='&:[ ]*:exit:ls:bg:fg:history:clear:*set-azure-pat*'

shopt -s cmdhist
shopt -s histappend
shopt -s histreedit
shopt -s histverify

alias h='history'
