#!/bin/bash

[[ $- == *i* ]] || return 0

bind "set completion-ignore-case on"
bind "set completion-map-case on"
bind "set mark-symlinked-directories on"
bind "set show-all-if-ambiguous on"
bind Space:magic-space

shopt -s autocd 2> /dev/null
shopt -s cdspell 2> /dev/null
shopt -s dirspell 2> /dev/null
shopt -s globstar 2> /dev/null

shopt -s cdable_vars
shopt -s checkhash
shopt -s checkwinsize
shopt -s dotglob
shopt -s extglob
shopt -s nocaseglob

umask 022
