---
- name: Set GDM login screen background color
  become: true
  command: gsettings set org.gnome.login-screen background-color "{{ gnome_settings_desktop_background }}"
  become_user: gdm
  when: gnome_settings_desktop_background is defined
