---
- name: Set GDM login screen background color
  become: yes
  command: gsettings set org.gnome.desktop.background primary-color "{{ desktop_background_color.stdout }}"
  become_user: gdm
  when: desktop_background_color.stdout != ""
