---
- name: Ensure /etc/gnome-initial-setup directory exists
  become: yes # noqa: yaml[truthy]
  file:
    path: /etc/gnome-initial-setup
    state: directory
    mode: "0755"

- name: Copy vendor.conf to /etc/gnome-initial-setup
  become: yes # noqa: yaml[truthy]
  copy:
    src: vendor.conf
    dest: /etc/gnome-initial-setup/vendor.conf
    mode: "0644"

