#!/bin/bash

# apt-get settings

APT_GET=$(command -v apt-get 2> /dev/null)

if [ -n $APT_GET ]; then

  SUDO=$(command -v sudo 2> /dev/null) || 'sudo'

  alias aptupd="$SUDO $APT_GET update"
  alias aptinst="$SUDO $APT_GET install --fix-broken --auto-remove -V"

fi
