#!/bin/bash

RUBY=$(command -v ruby &> /dev/null)

if [[ -n $RUBY ]]; then

  rbenv_bin=$(command -v rbenv &>/dev/null)
  if [[ -d $HOME/.rbenv ]] && [[ -n $rbenv_bin ]]; then
    PATH="$HOME/.rbenv/plugins/ruby-build/bin:$HOME/.rbenv/bin:${PATH}"
    eval "$(rbenv init -)"
  fi

  declare -x GEM_HOME
  GEM_HOME=$($RUBY -e 'print Gem.user_dir')

  export PATH="${GEM_HOME}/bin:${PATH}"

  [[ -d $HOME/.rvm/bin         ]] && PATH="${PATH}:$HOME/.rvm/bin"
  [[ -f $HOME/.rvm/scripts/rvm ]] && source "$HOME/.rvm/scripts/rvm"

  if [[ -d $HOME/.rbenv ]]; then
    eval "$(rbenv init -)"

  fi

  [[ -f $HOME/.rvm//scripts/completion ]] && source "$HOME/.rvm/scripts/completion"

fi
