#!/bin/bash

RUBY=$(command -v ruby)

if [ $? -eq 0 ]; then

  export GEM_HOME=$($RUBY -e 'print Gem.user_dir')
  export PATH="${GEM_HOME}/bin:${PATH}"

  [[ -d $HOME/.rvm/bin         ]] && PATH="${PATH}:~/.rvm/bin"
  [[ -f $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

  if [[ -d $HOME/.rbenv ]]; then
    eval "$(rbenv init -)"

  fi

  [[ -f $HOME/.rvm//scripts/completion ]] && source $HOME/.rvm/scripts/completion

fi
