#!/bin/bash

# less setup

export LESS='--hilite-search --IGNORE-CASE --status-column --RAW-CONTROL-CHARS --hilite-unread --tabs=2 -X'

# http://www-zeuthen.desy.de/~friebel/unix/lesspipe.html
# XXX: figure out how to make syntax hilighting work for source

# Try to use a more current lesspipe
lesspipe=$(command -v lesspipe.sh)

if [ $? -eq 0 ]; then

  export LESSOPEN="|${lesspipe} %s"

else

  # Fall back to system lesspipe, if it exists
  lesspipe=$(command -v lesspipe)

  if [ $? -eq 0 ]; then

    eval "$(SHELL=/bin/sh ${lesspipe})"

  fi
fi
