#!/bin/bash

# Debug tty login (ssh user@server):
# ssh -t localhost "PS4='[\$BASH_SOURCE[0]:\$LINENO]: ' bash -xl" |& tee login.log

# Debug no tty login (ssh user@server somecommand)
# ssh localhost "PS4='[\$BASH_SOURCE[0]:\$LINENO]: ' bash -xl" |& tee login.log

#-----------------------------------------------------------------------------
# Use these functions to clean up the environment at end of startup.
#
# Add any various variables or functions that you want to unset to the
# appropriate array.
#
# Usage:
#   unsetvars 'varname'
#   unsetfuncs 'funcname'

declare -a _unset_vars _unset_funcs

unsetvars() { _unset_vars+=("$@"); }
unsetfuncs() { _unset_funcs+=("$@"); }

#-----------------------------------------------------------------------------
# XXX: FIXME
# Setup for git bash on windows.
# o If MSYS is not set, then link is just a copy of stuff.
# o If MSYS is winsymlinks, it creates a Windows shortcut.
# o If MSYS is winsymlinks:nativestrict, it creates a more real type of symlink
#export MSYS="winsymlinks:nativestrict"

##############################################################################
# Base Global variable and path

#-----------------------------------------------------------------------------
# Assume that this file is in the dotfiles directory, then check if we are
# linnked to the dotfiles directory.  If we are, then use the real directory
# as the dotfiles directory.

declare -x DOTFILES="$HOME"
[[ -L ${BASH_SOURCE[0]} ]] \
  && DOTFILES=$(dirname "$(readlink -nf "${BASH_SOURCE[0]}")")

# Export initial path settings
export PATH="$DOTFILES/bin:$PATH"

#-----------------------------------------------------------------------------
# XDG Variables

export XDG_CONFIG_HOME="$DOTFILES/config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

mkdir -p "$XDG_CACHE_HOME"

export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"

export EDITOR=vim
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

##############################################################################
# Functions

#-----------------------------------------------------------------------------
# Set a default debug and, if set, check if debug is available and source it.

debug() { true; }
[[ -n $DEBUG ]] \
  && [[ -f "$DOTFILES/bin/debug" ]] \
  && source "$DOTFILES/bin/debug"

unsetfuncs 'debug'

#-----------------------------------------------------------------------------
# Add a path to the PATH variable.  This is a function so that we can
# easily add paths to the PATH variable.
#
# Usage:
#   addpath PATH /path/to/add
#   addpath LD_LIBRARY_PATH /path/to/add
#   andpath /path/to/add
#
#   The last one defaults to PATH

# XXX: Convert this to an external library.

addpath() {
  local target="PATH"

  if [[ $1 == "PATH" ]] || [[ $1 == "LD_LIBRARY_PATH" ]]; then
    target="$1"
    shift
  fi

  for p in "$@"; do
    [[ -z $p ]] && continue
    debug "adding $p to $target"
    printf -v "$target" "%s:%s" "${!target}" "$p"
  done
}

unsetfuncs 'addpath'

#-----------------------------------------------------------------------------
run_hook() {
  local hook="$dfdir/$1"
  debug "running hook: $hook"
  [[ -r $hook ]] || { debug "hook not readable: $hook"; return 1; }
  source "$hook" || { debug "hook failed: $hook"; return 1; }
  return 0
}

unsetfuncs 'run_hook'

#-----------------------------------------------------------------------------
# Add custom binary directories to the system's PATH variable, allowing users
# to execute their own scripts and commands from the command line. It reads the
# directory paths from a configuration file and appends them to the PATH
# variable in the specified order.
#
# This is not cumulative, either the defaults or the custom bin dirs are used.

# XXX: Add documentation for deault bin dirs.

set_bin_dirs() {
  bin_dirs_file="$DOTFILES/bin-dirs-defaults"
  [[ -r "$HOME/.bin-dirs" ]] && bin_dirs_file="$HOME/.bin-dirs"
  readarray -t bin_dirs < <(grep -v '^[[:space:]]*#' "$bin_dirs_file" | envsubst)
  addpath "${bin_dirs[@]}"
}

#-----------------------------------------------------------------------------
load_files() {
  declare -a load_dirs
  load_dirs+=("$XDG_CONFIG_HOME/shell-startup")
  load_dirs+=("$HOME/.shell_startup.d")

  # Run each directory instead of doing a find on all directories at once
  # because we want these files loaded in this particular order.

  for load_dir in "${load_dirs[@]}"; do
    [[ -d $load_dir ]] || continue

    readarray -t load_files < <(/usr/bin/find "$load_dir" -type f -not -iname '*_inactive' | /usr/bin/sort)

    for f in "${load_files[@]}"; do
      [[ -r $f ]] && source "$f"
    done
  done
}

##############################################################################
# Setup environment

path_to_generate_exports_script="/path/to/generate_exports.sh"
path_to_exports_script="/path/to/exports.sh"

# Generate export commands if needed
if [[ -x "$path_to_generate_exports_script" ]]; then
  source "$path_to_generate_exports_script"
fi

# Source the export commands
if [[ -r "$path_to_exports_script" ]]; then
  source "$path_to_exports_script"
fi

[[ -r "$DOTFILES/app_env_vars" ]] && source "$DOTFILES/app_env_vars"

[[ -r "$DOTFILES/shell_startup.d/pre-setup" ]] \
  && source "$DOTFILES/shell_startup.d/pre-setup"

#-----------------------------------------------------------------------------
# Check if various dotfiles are linked properly
[[ -x "$(command -v check-dotfiles 2> /dev/null)" ]] && check-dotfiles

set_bin_dirs
load_files

set_bin_dirs
load_files

##############################################################################
# Cleanup

unset -f "${_unset_funcs[@]}"
unset "${_unset_vars[@]}"
unset -f unsetvars unsetfuncs
unset _unset_vars _unset_funcs
