#!/bin/bash

# If bash-completion is installed, CDPATH is searched for completions.
CDPATH=".:$HOME/projects:$HOME/projects/zions"

PROMPT_DIRTRIM=2

export EDITOR=vim
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

command -v chromium-browser &> /dev/null && export BROWSER='chromium-browser'
