#!/bin/bash

# Environment variables for ruby

if command -v ruby &> /dev/null; then

  if command -v rbenv &> /dev/null; then
    [[ -d $HOME/.rbenv ]] && PATH="$HOME/.rbenv/plugins/ruby-build/bin:$HOME/.rbenv/bin:$PATH"
  fi

  declare -x GEM_HOME
  GEM_HOME=$(ruby -e 'print Gem.user_dir')

  export PATH="$GEM_HOME/bin:$PATH"

  [[ -d $HOME/.rvm/bin ]] && PATH="$PATH:$HOME/.rvm/bin"
fi
