#!/bin/bash

cache_dir="$PWD"
paths_file='mock-vault-paths.json'
mode=

case "$1" in
  debug) mode='pudb' ;;
  echo) mode='echo' ;;
esac

$mode ./get-vault-key.py \
  list "production" \
  --cache-dir \"$cache_dir\" \
  --paths-file \"$paths_file\"

