#!bash

type -P go &> /dev/null || return 0

#----------------------------------------------------------------------
if [ -z "$GOPATH" ]; then
    if [ -n "$(go env GOPATH)" ]; then
        export GOPATH="$(go env GOPATH)"
    else
        export GOPATH="$HOME/go"
    fi

    mkdir -p "$GOPATH"
    addpath "$GOPATH"
fi

#----------------------------------------------------------------------
if [ -z "$GOBIN" ]; then
    if [ -n "$(go env GOBIN)" ]; then
        export GOBIN="$(go env GOBIN)"
    else
        export GOBIN="$GOPATH/bin"
    fi

    mkdir -p "$GOBIN"
    addpath "$GOBIN"
fi

true
