#!/bin/bash

command -v go &> /dev/null || return 0

export GOROOT=$(go env GOROOT)
export GOPATH=$(go env GOPATH)
export GOBIN="$HOME/.go/bin"

addpath "$GOBIN"
addpath "$GOROOT/bin"
addpath "${GOPATH//://bin:}/bin"

true
