#!/bin/bash

[[ $- == *i* ]] || return 0

_ssh() {
  readarray -t SSH_KNOWN_HOSTS < <(awk '{print $1}' ~/.ssh/known_hosts | cut -d ',' -f 1 | uniq | grep -v 'localhost')
  read -ra SSH_CONFIG_HOSTS < <(grep 'Host ' ~/.ssh/config | cut -d ' ' -f 2- | tr '\n' ' ' | uniq)
  complete -o default -W "${SSH_KNOWN_HOSTS[*]} ${SSH_CONFIG_HOSTS[*]}" ssh
}

complete -F _ssh ssh
