#!/bin/bash

debug "Setting up dir_readable ..."

function __dir_readable() {
  debug "Entering ${FUNCNAME[0]} ..."

  local pwd_max=45 # How long before we truncate?
  local trunc='<'  # Mark truncated name with this.

  local readable
  if [ -w "${PWD}" ]; then readable="$(ansi fg green)"; else readable="$(ansi fg red)"; fi

  local pwd=$PWD

  if [ ${#pwd} -gt $pwd_max ]; then # truncate on the left

    local pwd_offset=$(( ${#PWD} - pwd_max ))
    pwd="${trunc}${pwd:$pwd_offset:$pwd_max}"

  fi

  debug "... exiting ${FUNCNAME[0]}."
  echo "$readable$pwd$(ansi off)"

}

deub "... done setting up dir_readable."
