#!/bin/bash

debug "Setting up dropbox ..."

if command -v dropbox &>/dev/null; then
  function __dropbox_status() {
    debug "Entering and exiting ${FUNCNAME[0]}."
    echo "Dropbox: $(dropbox status)"
  }
fi

debug "... done setting up drobpox."
