#!/bin/bash

if command -v pacman &>/dev/null; then
  function __pacman_status() {

    #local now=$(date +%s)
    local update_duration='-'

    local last_update
    last_update=$(grep -a "starting full system upgrade" /var/log/pacman.log | tail -1 | cut -c2-17)

    [[ -n $last_update ]] && update_duration=$(__duration "$last_update")

    if echo "$update_duration" | grep -q '[234]d'; then
      update_duration="$(ansi fg yellow)$update_duration$(ansi off)"

    elif echo "$update_duration" | grep -q '1d'; then
      update_duration="$(ansi fg green)$update_duration$(ansi off)"

    elif echo "$update_duration" | grep -q '[[:digit:]]d'; then
      update_duration="$(ansi fg red)$update_duration$(ansi off)"

    else
      update_duration="$(ansi fg green)$update_duration$(ansi off)"

    fi

    echo "Pacman Last Updated: $update_duration"

  }

else
  function __pacman_status { :; }

fi
