#!/bin/bash

function __parent_process() {

  local parents

  parents=$(pstree -A $PPID 2> /dev/null) || { return 1 ; }

  parents=${parents/%-+*/}
  parents=${parents//tmux/}
  parents=${parents//---bash/}
  parents=${parents//---pstree/}
  parents=${parents//gnome-terminal-}

  [[ -n $parents ]] && printf '\[%s\](%s)\[%s\]' "$(ansi fg bright_yellow bg red)" "$parents" "$(ansi off)"

}
