#!/bin/bash

function __sysinfo() {
  declare -a sysinfo_part
  # shellcheck disable=SC1117
  sysinfo_part+=("Uptime: \$(perl -ne 's/\s.*\$//;printf\"%.2f\",\$_/(60*60*24)' /proc/uptime) days") # uptime
  sysinfo_part+=("LoadAvg: \$(cat /proc/loadavg | cut -d ' ' -f 1-3)")                                # loadavg
  sysinfo_part+=("\$(df -hP . | grep -v 'Avail' | tr -s ' ' | cut -d ' ' -f 4) available")            # freespace

  join_array ' | ' "${sysinfo_part[@]}"
}
