#!/bin/bash

function __versions () {

  local versionline

  perlv='not installed'
  if command -v perl > /dev/null; then
    perlv=$(perl -e 'print $]')
  fi

  pythonv='not installed'
  if command -v python > /dev/null; then
    pythonv=$(python -V 2>&1 | cut -d ' ' -f 2)
  fi

  rubyv='not installed'
  if command -v ruby > /dev/null; then
    rubyv=$(ruby -v | cut -d ' ' -f 2)
  fi

  # Version line

  local -a  versions
  versions+=("$(uname -sr)")
  versions+=("Perl $perlv")
  versions+=("Python $pythonv")
  versions+=("Ruby $rubyv")

  versionline=$(join_array ' | ' 'versions')

  echo "$versionline"

}
