---
- name: Load version tracking information
  include_tasks: load_versions.yml
  when: version_tracking_action == 'load'

- name: Update version tracking information for a specific key
  set_fact:
    version_tracking: "{{ version_tracking | combine({ version_tracking_key: version_tracking_value }) }}"
  when:
    - version_tracking_key is defined
    - version_tracking_value is defined
    - version_tracking_action == 'update'

- name: Save version tracking fact to YAML file
  copy:
    dest: "{{ version_tracking_file }}"
    content: "{{ version_tracking | to_nice_yaml }}"
  when:
    - version_tracking is defined
    - version_tracking_action == 'save'
