---
- name: Verify required autostart variables are defined
  fail:
    msg: Required variable '{{ item }}' is not defined for autostart configuration.
  when: item is not defined
  with_items:
    - autostart_app_name
    - autostart_app_type
    - autostart_app_settings

- name: Verify autostart_app_type has a valid value
  fail:
    msg: The autostart_app_type variable must be one of 'Application', 'Link', or 'Directory'.
  when: autostart_app_type not in ['Application', 'Link', 'Directory']

- name: Verify Exec key for Application type in autostart_app_settings
  fail:
    msg: The 'Exec' key must be defined and not empty in autostart_app_settings for Application type.
  when: autostart_app_type == 'Application' and ('Exec' not in autostart_app_settings or not autostart_app_settings['Exec'])

- name: Verify URL key for Link type in autostart_app_settings
  fail:
    msg: The 'URL' key must be defined and not empty in autostart_app_settings for Link type.
  when: autostart_app_type == 'Link' and ('URL' not in autostart_app_settings or not autostart_app_settings['URL'])

- name: Create GNOME autostart directory if it doesn't exist
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory
    mode: "0755"

- name: Create autostart desktop entry
  template:
    src: autostart_app.desktop.j2
    dest: "{{ ansible_env.HOME }}/.config/autostart/{{ autostart_app_name }}.desktop"
    mode: "0644"
