---
- name: Disable gdm3 display manager
  become: yes # noqa: yaml[truthy]
  systemd:
    name: gdm3
    state: stopped
    enabled: false
    masked: true

- name: Ensure LightDM is the default display manager
  become: yes # noqa: yaml[truthy]
  lineinfile:
    path: /etc/X11/default-display-manager
    regexp: '^/usr/sbin/'
    line: '/usr/sbin/lightdm'
    mode: '0644'
    create: true

- name: Copy slick greeter seats conf
  become: yes # noqa: yaml[truthy]
  copy:
    src: 99-slick-greeter.conf
    dest: /etc/lightdm/lightdm.conf.d/99-slick-greeter.conf
    mode: "0644"

- name: Copy slick greeter conf
  become: yes # noqa: yaml[truthy]
  copy:
    src: slick-greeter.conf
    dest: /etc/lightdm/slick-greeter.conf
    mode: "0644"

- name: Enable LightDM display manager
  become: yes # noqa: yaml[truthy]
  systemd:
    name: lightdm
    state: started
    enabled: true
    daemon_reload: true

- name: Notice
  debug:
    msg: "Changes to lightdm won't take effect until next boot."
