---
dependencies:
  - role: add_repo
    vars:
      add_repo_filename: docker
      add_repo_key_url: https://download.docker.com/linux/ubuntu/gpg
      add_repo_name: Docker
      add_repo_urls:
        - "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
