#!/bin/bash

# If bash-completion is installed, CDPATH is searched for completions.
# XXX: What else do I need to put here?
CDPATH=".:$PRJHOME"

PROMPT_DIRTRIM=2

# XXX: what will break if I change this vim?
export EDITOR=vi
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
