#!/bin/bash

[[ -d "${GLOBAL_DIR}/tools/go/bin" ]] || return 0

export GOROOT="$GLOBAL_DIR/tools/go"
export GOPATH="$GLOBAL_DIR/tools/.go_src"
export GOBIN="$GOPATH/bin"

addpath "$GOBIN"
addpath "$GOROOT/bin"

true
