---
dependencies:
  - role: add_repo
    repo_list:
      - docker

  - role: install_pkgs
    vars:
      package_groups: "docker"
    pre_tasks:
      - name: Remove older Docker packages
        apt:
          name:
            - docker
            - docker-engine
            - docker.io
            - containerd
            - runc
          state: absent
          purge: yes
  - role: install_pkgs
    vars:
      package_groups: "docker"
