#!/bin/bash

FIND='/usr/bin/find'
SORT='/usr/bin/sort'
HEAD='/usr/bin/head'

MOVE_DAYS_OLD='+30'
#MOVE_HOW_MANY=20
REMOVE_DAYS_OLD='+30'
SOURCE_PATH='/home/media2/movies/alpha'
TOBEDELETED_PATH='/home/media/movies/ToBeDeleted'

mkdir -p $TOBEDELETED_PATH

#for movie in $($FIND $SOURCE_PATH/[A-Z_] -atime $MOVE_DAYS_OLD -type f | $SORT -R | $HEAD -n $MOVE_HOW_MANY); do
for movie in $($FIND $SOURCE_PATH/[A-Z_] -atime $MOVE_DAYS_OLD -type f); do

  echo Moving $movie
  touch $movie
  mv $movie $TOBEDELETED_PATH

done

for movie in $($FIND $TOBEDELETED_PATH -atime $REMOVE_DAYS_OLD -type f); do

  echo Removing $movie
  rm $movie

done
