#!/bin/bash

function pastebinit() { "$@" | curl -F 'sprunge=<-' http://sprunge.us; }

##################
# Get an ordered list of subdirectory sizes
# http://www.shell-fu.org/lister.php?id=275

function dusk() {
  du -sk ./* \
    | sort -n \
    | awk '
BEGIN{ pref[1]="K"; pref[2]="M"; pref[3]="G";}

{ total = total + $1; x = $1; y = 1;
  while( x > 1024 ) {
    x = (x + 1023)/1024; y++;
  }
  printf("%g%s\t%s\n",int(x*10)/10,pref[y],$2);
}

END {
  y = 1;
  while( total > 1024 ) {
    total = (total + 1023)/1024; y++;
  }
  printf("Total: %g%s\n",int(total*10)/10,pref[y]);
}'
}


######################################################################################

# Don't remember where I got this. Returns true if the current terminal can do
# 256 colors, otherwise it returns false.
can256() { [ "$(tput Co 2> /dev/null || tput colors 2> /dev/null || echo 0)" -gt 2 ]; }

# bash-completion for aliases
# https://unix.stackexchange.com/questions/4219/how-do-i-get-bash-completion-for-command-aliases
# http://ubuntuforums.org/showthread.php?t=733397

# alias gco='git checkout'
# make-completion-wrapper _git _git_checkout git checkout
# complete -F _git_checkout gco

# This doesn't work. At least for git.

# See also:
# https://stackoverflow.com/questions/342969/how-do-i-get-bash-completion-to-work-with-aliases

# shellcheck disable=SC2124,2027
function make-completion-wrapper() {
  local function_name="$2"
  local arg_count=$(($# - 3))
  local comp_function_name="$1"
  shift 2
  local function="
    function $function_name {
      ((COMP_CWORD+=$arg_count))
      COMP_WORDS=( $@ \${COMP_WORDS[@]:1} )
      "$comp_function_name"
      return 0
    }"
  eval "$function"
  echo "$function_name"
  echo "$function"
}
