#!/bin/bash

# See the 'How to use GIT checkout' section of the README.rst file.

FLEXGET_DIR='/home/harleypig/projects/flexget'

cd $FLEXGET_DIR || {
  echo "Unable to change to $FLEXGET_DIR, exiting"
  exit 1
}

set_title "$(basename "$0")"

bin/flexget daemon stop

while (pgrep -x flexget 1>/dev/null 2>&1); do
  dots="${dots}."
  echo -ne "waiting for flexget to stop $dots\r"
  sleep 1
done

echo

# start clean
git clean -xf

# update flexget
git fetch --all --tags
git pull
virtualenv --clear --always-copy .
bin/pip install --upgrade -r requirements.txt
bin/python setup.py develop
bin/pip install --upgrade -e .
bin/flexget check || echo "Config did not pass check, see https://flexget.com/UpgradeActions for possible info."
bin/flexget database cleanup
bin/flexget database vacuum
bin/flexget daemon start -d

set_title 'done_updating'
