---
- name: Download the latest binenv release from GitHub
  become: yes
  get_url:
    url: "https://github.com/devops-works/binenv/releases/latest/download/binenv_linux_amd64"
    dest: "/tmp/binenv"
    mode: '0700'

- name: Update package list
  become: yes
  command: /tmp/binenv -g update

- name: Use binenv to install binenv
  become: yes
  command: /tmp/binenv -g install binenv

- name: Install specified packages using binenv
  become: yes
  command: binenv -g install {{ item }}
  loop: "{{ binenv_packages }}"
