---
- name: Add APT Repository
  hosts: localhost
  become: yes
  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - key_url is defined
          - repo_url is defined
          - filename is defined
          - repo_name is defined
        fail_msg: "Required variable is not defined."
  tasks:
    - name: "Install Repository Public Key for {{ repo_name }}"
      apt_key:
        url: "{{ key_url }}"
        state: present

    - name: "Add APT repository for {{ repo_name }}"
      apt_repository:
        repo: "{{ repo_url }}"
        filename: "{{ filename }}"
        state: present
