---
- name: Add APT Repository
  hosts: localhost
  become: yes
  tasks:
    - name: "Install Repository Public Key for {{ repo_name }}"
      apt_key:
        url: "{{ key_url }}"
        state: present

    - name: "Add APT repository for {{ repo_name }}"
      apt_repository:
        repo: "{{ repo_url }}"
        filename: "{{ filename }}"
        state: present
