- name: Common Packages
  hosts: localhost
  become: yes

  #debugger: on_failed

  tasks:
    - name: Install Common Packages
      apt:
        state: present
        name:
          - ansible
          - ansible-lint
          - aptitude
          - docker
          - docker-compose
          - dos2unix
          - expect
          - elinks
          - git
          - jq
          - markdown
          - mlocate
          - pandoc
          - tmux
