#!/bin/bash

# This script dumps all dconf settings that are not the same as their default values.

DUMP_FILE="dconf-changes.dump"

# Dump all non-default dconf settings to a file
dconf dump / | awk -F= '/^\[/{ if (schema) print schema; schema=$0; next } /^[^#]/ { print $0 } END { if (schema) print schema }' | \
awk -v dump_file="$DUMP_FILE" '
{
    if ($0 ~ /^\[/) {
        if (schema) {
            # Output the schema block if it has non-default settings
            if (length(settings) > 0) {
                print schema >> dump_file
                for (setting in settings) {
                    print setting >> dump_file
                }
                print "" >> dump_file # Add an empty line after the block
            }
            delete settings
        }
        schema=$0
    } else {
        split($0, kv, "=")
        key=kv[1]
        value=kv[2]
        default_value=system("dconf read " schema "/" key)
        if (default_value != value) {
            settings[key"="value]
        }
    }
}
END {
    if (length(settings) > 0) {
        print schema >> dump_file
        for (setting in settings) {
            print setting >> dump_file
        }
    }
}'



echo "Non-default dconf settings have been dumped to $DUMP_FILE"
