#!/bin/bash

# This script dumps all dconf settings that are not the same as their default values.

DUMP_FILE="dconf-changes.dump"

# Dump all non-default dconf settings to a file
dconf dump / | awk -F= '/^\[/{ gsub(/\[/, "", $1); gsub(/\]/, "", $1); schema=$1; next } /^[^#]/ { print schema "=" $1 }' | \
sort -t= -k2,2 | \
while IFS= read -r entry; do
    schema=$(echo "$entry" | cut -d= -f1)
    key=$(echo "$entry" | cut -d= -f2)
    value=$(echo "$entry" | cut -d= -f3-)
    default_value=$(dconf read "/$schema/$key")
    if [[ "$default_value" != "$value" ]]; then
        echo "[$schema]" >> "$DUMP_FILE"
        echo "$key=$value" >> "$DUMP_FILE"
    fi
done


echo "Non-default dconf settings have been dumped to $DUMP_FILE"
