- name: GUI Packages
  hosts: localhost
  become: yes

  #debugger: on_failed

  tasks:
    - name: Install GUI Packages
      apt:
        state: present
        name:
          - fonts-inconsolata
          - gnome-tweaks
          - tilix

    - name: Check if Tilix profile file exists
      stat:
        path: "{{ playbook_dir }}/tilix-profile.dconf"
      register: tilix_profile_file

    #- name: Debug Tilix profile file existence
    #  debug:
    #    msg: "Tilix profile file exists: {{ tilix_profile_file.stat.exists }}"

    - name: Load Tilix profile if file exists
      command: dconf load /com/gexperts/Tilix/ < "{{ playbook_dir }}/tilix-profile.dconf"
      when: tilix_profile_file.stat.exists
      notify: Restart Tilix
