- name: GUI Packages
  hosts: localhost
  #become: yes

  #debugger: on_failed

  vars:
    tilix_profile_filename: "{{ playbook_dir }}/tilix-profile.dconf"

  tasks:
    - name: Install GUI Packages
      become: yes
      apt:
        state: present
        name:
          - fonts-inconsolata
          - gnome-tweaks
          - tilix

    - name: Check if Tilix profile file exists
      stat:
        path: "{{ tilix_profile_filename }}"
      register: tilix_profile_file

    - name: Load Tilix profile if file exists
      shell: "dconf load /com/gexperts/Tilix/ < {{ tilix_profile_filename }}"
      when: tilix_profile_file.stat.exists
      notify: Restart Tilix
