- name: hledger Packages
  hosts: localhost
  become: yes

  #debugger: on_failed

  tasks:
    - name: Install Common Packages
      apt:
        state: latest
        update_cache: yes
        name:
          - hledger
          - hledger-ui
