- name: Hashicorp Repository
  hosts: localhost
  become: yes

  vars:
    key_url: https://apt.releases.hashicorp.com/gpg
    repo_url: deb https://apt.releases.hashicorp.com focal main
    filename: hashicorp

  tasks:
    - name: Install Hashicorp Repository Public Key
      apt_key:
        url: "{{ key_url }}"
        state: present

    - name: Add Hashicorp Repository
      apt_repository:
        repo: "{{ repo_url }}"
        filename: "{{ filename }}"
        state: present
