- name: Hashicorp Repository
  hosts: localhost
  become: yes

  vars:
    key_url: https://apt.releases.hashicorp.com/gpg
    repo_url: deb https://apt.releases.hashicorp.com focal main
    filename: hashicorp
    repo_name: Hashicorp

  tasks:
    - include_tasks: repo-add.yml
