---
- hosts: localhost
  become: yes

  roles:
    - role: install_pkgs
    - role: nerd_font
    - role: add_repo
      vars:
        repo_list:
          - nodesource
    - role: gnome_settings
      vars:
        gnome_settings_tilix_profile_filename: "{{ playbook_dir }}/harleypig-tilix-profile.dconf"

    #- role: install_pkgs
    - role: pip_pkgs
    - role: add_iac
    - role: git_bug
    - role: docker
