---
- name: Setup Sweetums environment
  hosts: localhost
  become: true

  roles:
    - role: install_pkgs
    - role: nerd_font
    - role: gnome_settings
      vars:
        gnome_settings_tilix_profile_filename: "{{ playbook_dir }}/harleypig-tilix-profile.dconf"

    - role: nodejs
    - role: pip_pkgs
    - role: add_iac
    - role: git_bug
    - role: docker
