---
- name: Setup Sweetums environment
  hosts: localhost

  vars:
    version_tracking_file: .github-release-tracking-file.yml

  roles:
    - role: install_pkgs
    - role: nerd_font
    - role: gnome_settings
      vars:
        gnome_settings_tilix_profile_filename: "{{ playbook_dir }}/harleypig-tilix-profile.dconf"

    - role: nodejs
    - role: pip_pkgs
    - role: hashicorp
    - role: git_bug
    - role: docker
