---
- hosts: localhost
  become: yes

  roles:
    - role: gnome_settings
      tilix_profile_filename: "{{ playbook_dir }}/harleypig-tilix-profile.dconf"

    - role: install_pkgs
    - role: pip_pkgs
    - role: nerd_font
    - role: add_iac
    - role: git_bug
