---
- name: Setup Sweetums environment
  hosts: localhost

  vars:
    version_tracking_file: .version-tracking-file.yml

  roles:
    - role: version_tracking
    - role: cli_pkgs
    # ???: https://github.com/ctorgalson/ansible-role-nerdfonts
    #      https://github.com/hurricanehrndz/ansible-nerdfonts
    #      https://github.com/gikeymarcia/ansible-role-nerdfonts
    #- role: nerd_font
    - role: nodejs
    - role: pip_pkgs
    - role: hashicorp
    #- role: git_bug
    - role: gh_cli
    - role: docker
    - role: misc_configuration

    #- role: gnome_settings
    #  vars:
    #    gnome_settings_tilix_profile_filename: "{{ playbook_dir }}/harleypig-tilix-profile.dconf"

    - role: version_tracking
      vars:
        version_tracking_action: 'save'
