---
- name: Test roles
  hosts: localhost

  vars:
    version_tracking_file: .version-tracking-file.yml

  roles:
    #- role: version_tracking
    # - role: git_bug
    # - role: gnome_settings
    #  vars:
    #    gnome_settings_tilix_profile_filename: "{{ playbook_dir }}/harleypig-tilix-profile.dconf"
    #- role: hashicorp
    #- role: gcloud
    - role: nodejs

    #- role: version_tracking
    #  vars:
    #    version_tracking_action: 'save'
