---
- name: Test roles
  hosts: localhost

  vars:
    version_tracking_file: .version-tracking-file.yml

  roles:
    # - role: git_bug
    - role: gnome_settings
      vars:
        gnome_settings_tilix_profile_filename: "{{ playbook_dir }}/harleypig-tilix-profile.dconf"
