---
- hosts: localhost
  become: yes
  roles:
    - { role: docker }
  hosts: localhost

  vars:
    version_tracking_file: .version-tracking-file.yml

  roles:
    #- role: hashicorp
    role: docker
