---
- hosts: localhost

  roles:
    #- role: docker
    #- role: nodejs
    #- role: git_bug
    - role: github_release
      vars:
        github_repo: terraform-linters/tflint
        github_asset_name: tflint
        github_asset_pattern: tflint_linux_amd64.zip
        github_dest_path: /usr/local/bin/tflint
        github_dest_path_mode: "0755"
