- name: Tilix Profile Setup
  hosts: localhost
  become: yes

  tasks:
    - name: Check if Tilix profile file exists
      stat:
        path: "{{ playbook_dir }}/tilix-profile.dconf"
      register: tilix_profile_file

    - name: Load Tilix profile if file exists
      command: dconf load /com/gexperts/Tilix/ < "{{ playbook_dir }}/tilix-profile.dconf"
      when: tilix_profile_file.stat.exists
      notify: Restart Tilix

