- name: Tilix Profile Setup
  hosts: localhost
  become: yes

  tasks:
    - name: Check if Tilix profile is already imported
      command: dconf load /com/gexperts/Tilix/ < /path/to/tilix-profile.dconf
      register: tilix_profile_import
      failed_when: tilix_profile_import.rc != 0 and 'No such file' not in tilix_profile_import.stderr
      changed_when: 'No such file' in tilix_profile_import.stderr

    - name: Import Tilix profile
      command: dconf load /com/gexperts/Tilix/ < "{{ playbook_dir }}/tilix-profile.dconf"
      when: tilix_profile_import is changed
      notify: Restart Tilix
