---
- hosts: localhost
  become: yes

  roles:
    - role: install_pkgs
      is_exclude_list: true
      exclude_group:
        - hledger
    - role: pip_pkgs
      is_exclude_list: true
      exclude_group:
        - linode
    - role: nerd_font
    - role: add_iac
    - role: git_bug
    - role: gnome_settings
      tilix_profile_filename: "{{ playbook_dir }}/harleypig-tilix-profile.dconf"
    - role: gnome_settings
