---
- hosts: localhost
  become: true

  roles:
    - role: install_pkgs
    - role: nerd_font
    - role: nodejs

    - role: gnome_settings
      vars:
        gnome_settings_tilix_profile_filename: "{{ playbook_dir }}/harleypig-tilix-profile.dconf"

    - role: pip_pkgs
      pip_pkgs_is_exclude_list: true
      pip_pkgs_exclude_group:
        - linode

    - role: add_iac
    - role: docker
    - role: gcloud
    - role: vscode
