---
- hosts: localhost
  become: yes

  roles:
    - role: install_pkgs
      exclude_group: ['hledger']
      is_exclude_list: true
    - role: nerd_font
    - role: add_iac
    - role: git_bug
    - role: gnome_settings
