#!bash

export GOPATH="${XDG_DATA_HOME}/go"

type -P go &> /dev/null || return 0

#----------------------------------------------------------------------
if [ -z "$GOBIN" ]; then
    if [ -n "$(go env GOBIN)" ]; then
        export GOBIN="$(go env GOBIN)"
    else
        export GOBIN="$GOPATH/bin"
    fi

    mkdir -p "$GOBIN"
    addpath "$GOBIN"
fi
