#!/bin/bash

# less setup

export LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
# See man less for other LESSKEY options
#export LESSKEY="${XDG_CONFIG_HOME}/less/lesskey"

export LESS='--hilite-search --IGNORE-CASE --status-column --RAW-CONTROL-CHARS --hilite-unread --tabs=2 -X'

# This will color man output, but also any less outupt with the proper codes embedded.

#------------------------------------------------------
# blink

LESS_TERMCAP_mb="$(ansi fg bright_red)"
export LESS_TERMCAP_mb

#------------------------------------------------------
# bold open/close (used for HEAD1 and some other emphasis)

LESS_TERMCAP_md="$(ansi fg bright_purple)"
export LESS_TERMCAP_md

LESS_TERMCAP_me=$(ansi off)
export LESS_TERMCAP_me

#------------------------------------------------------
# standout open/close (used for prompt open/close?)

LESS_TERMCAP_so=$(ansi fg bright_yellow)
export LESS_TERMCAP_so

LESS_TERMCAP_se=$(ansi off)
export LESS_TERMCAP_se

#------------------------------------------------------
# underline open/close (used for?)

LESS_TERMCAP_us=$(ansi fg bright_green)
export LESS_TERMCAP_us

LESS_TERMCAP_ue=$(ansi off)
export LESS_TERMCAP_ue

#------------------------------------------------------
# reverse (used for?)

LESS_TERMCAP_mr=$(ansi rev)
export LESS_TERMCAP_mr

#------------------------------------------------------
# dim (used for?)
# Doesn't appear to be a tput command for dim, ignore this for now.

#LESS_TERMCAP_mh=$(ansi dim)
#export LESS_TERMCAP_mh

#------------------------------------------------------
# konsole and gnome-terminal require this
export GROFF_NO_SGR=1

# XXX: http://www-zeuthen.desy.de/~friebel/unix/lesspipe.html
# XXX: figure out how to make syntax hilighting work for source

# Try to use a more current lesspipe
lesspipe=$(command -v lesspipe.sh &>/dev/null)

if [[ -n $lesspipe ]]; then

  export LESSOPEN="|${lesspipe} %s"

else

  # Fall back to system lesspipe, if it exists
  lesspipe=$(command -v lesspipe &>/dev/null)

  if [[ -n $lesspipe ]]; then

    eval "$(SHELL=/bin/sh ${lesspipe})"

  fi
fi
