#!/bin/bash

# This should only be run from bash startup files.
# XXX: check for being sourced
# XXX: Document me!
# XXX: Test me!

# See https://unix.stackexchange.com/questions/4219/how-do-i-get-bash-completion-for-command-aliases
# for a way to add aliases to completion.

load_completions() {
  local local_completions="$DOTFILES/.bash_completion.d"

  local -a bcfiles=()

  bcfiles+=('/etc/bashrc')
  bcfiles+=('/etc/bash_completion')
  bcfiles+=('/etc/profile.d/bash-completion')

  [[ -d $local_completions ]] \
    && readarray -t -O "${#bcfiles[@]}" bcfiles < <(find "$local_completions" -type f)

  local bcfile

  for bcfile in "${bcfiles[@]}"; do
    [[ -r $bcfile ]] && {
      debug "Sourcing $bcfile ..."
      source "$bcfile" || debug "... unable to source $bcfile"
    }
  done
}

export -f load_completions
