#!/bin/bash

##############################################################################
# Final cleanup of PATH and LD_LIBRARY_PATH environment variables. There are
# some duplicate paths, some paths that don't exist and some paths should come
# at the beginning of the path, while others should appear at the end of the
# path.

#-----------------------------------------------------------------------------
warn() { printf '%s\n' "$@" >&2; }

die() {
  (($#)) && warn "$@"
  exit 1
}

debug() {
  ((DEBUG)) || return 0
  warn "$@"
}

#-----------------------------------------------------------------------------
get_real_dir() {
  local d=$1

  # What is the real path for $d?
  dir=$(readlink -ne "$d") || return 1

  # does $dir exist?
  [[ -z $dir ]] && return 1

  # is $dir a directory?
  [[ -d $dir ]] || return 1

  printf '%s' "$dir"
  return 0
}

#-----------------------------------------------------------------------------
# join with colon
# No, IFS=':' echo "$*" does not work.

jwc() {
  local IFS=':'
  echo "$*"
  return 0
}

#-----------------------------------------------------------------------------
declare -A SHOULD_BE_FIRST SHOULD_BE_LAST SHOULD_BE_IGNORED SHOULD_BE_STRIPPED

build_path() {
  local path="${1?Must pass path}"

  declare -a PATHS PATH_FIRST PATH_NEW PATH_LAST
  declare -A PATH_CHECK

  IFS=':' read -ra PATHS <<< "${!path}"

  for d in "${PATHS[@]}"; do
    debug "Checking $d ..."

    # Ignore blank entries
    [[ -z $d ]] && continue

    # Ignore dot
    [[ $d == '.' ]] && continue

    # Have we already handled this directory?
    [[ ${PATH_CHECK[$d]+isset} -ne 0 ]] && continue

    if [[ ${SHOULD_BE_IGNORED[$d]+isset} -ne 0 ]]; then
      PATH_NEW+=("$d")
      PATH_CHECK[$d]=1
      debug "IGNORE: $d"
      continue

    elif [[ ${SHOULD_BE_STRIPPED[$d]+isset} -ne 0 ]]; then
      PATH_CHECK[$dir]=1
      debug "STRIP: $d"
      continue
    fi

    # Get the real path, if it really exists.
    dir=$(get_real_dir "$d") || continue

    # Have we already handled this directory?
    [[ ${PATH_CHECK[$dir]+isset} -ne 0 ]] && continue

    if [[ ${SHOULD_BE_STRIPPED[$dir]+isset} -ne 0 ]]; then
      debug "STRIP: $dir"

    elif [[ ${SHOULD_BE_FIRST[$dir]+isset} -ne 0 ]]; then
      PATH_FIRST+=("$dir")
      debug "FIRST: $dir"

    elif [[ ${SHOULD_BE_LAST[$dir]+isset} -ne 0 ]]; then
      PATH_LAST+=("$dir")
      debug "LAST: $dir"

    else
      PATH_NEW+=("$dir")
      debug "DIR: $dir"
    fi

    PATH_CHECK[$dir]=1
  done

  jwc "${PATH_FIRST[@]}" "${PATH_NEW[@]}" "${PATH_LAST[@]}"

  return 0
}

#-----------------------------------------------------------------------------
[[ -z $1 ]] && die "No environment variable name passed as parameter."
[[ -z ${!1} ]] && die "Environment variable '$1' does not exist."

#-----------------------------------------------------------------------------
# Entries in PATH_SHOULD_BE_{FIRST,LAST} should be the 'real' path; i.e., the
# path returned from the above 'get_real_dir' function.

# These paths should appear at the beginning of the PATH list.
#PATH_SHOULD_BE_FIRST['/first']=1

# These paths should appear at the end of the PATH list.
#SHOULD_BE_LAST['/last']=1

#-----------------------------------------------------------------------------
# Cleanup PATH variable
debug "Cleaning path ..."

#SHOULD_BE_FIRST=()
#SHOULD_BE_LAST=()
#SHOULD_BE_IGNORED=()
#SHOULD_BE_STRIPPED=()

NEWPATH=$(build_path 'PATH')
export PATH="$NEWPATH:."

#-----------------------------------------------------------------------------
# Cleanup LD_LIBRARY_PATH variable
debug "Cleaning ld library path ..."

LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib:/usr/lib64"

SHOULD_BE_FIRST=()
#SHOULD_BE_LAST=()
#SHOULD_BE_IGNORED=()
#SHOULD_BE_STRIPPED=()

SHOULD_BE_FIRST['/usr/lib']=1
SHOULD_BE_FIRST['/usr/lib64']=1

NEWLDPATH=$(build_path 'LD_LIBRARY_PATH')
export LD_LIBRARY_PATH="$NEWLDPATH"

#-----------------------------------------------------------------------------
# Don't clutter the environment in case we are being sourced.

unset -f get_real_dir jwc build_path debug addpath
unset NEWPATH NEWLDPATH SHOULD_BE_FIRST SHOULD_BE_LAST
unset SHOULD_BE_IGNORED SHOULD_BE_STRIPPED f
