- name: Install MYPROJECT
  hosts: loclhost
  become: true

  #debugger: on_failed

  vars:
    package_name: 
    project_repo: 
    project_dir: $HOME/projects/MYPROJECT

  tasks:
    - name: Ensure package is not installed
      apt:
        name: {{ package_name }}
        state: absent

    - name: Clone project repo
      git:
        repo: {{ project_repo }}
        dest: {{ project_dir }}
        version: master
      register: git_result

    - name: Compile project if necessary
      shell: make
      args:
        chdir: {{ project_dir }}
      when: git_result.changed

    - name: Install project
      shell: make install
      args:
        chdir: {{ project_dir }}

