cmdargs:
  verbose: no
  severity: style_problem
  error-limit: 50
  stat: no
  color: no
  json: no
  env:
    neovim: no
  stdin_display_name: stdin

policies:
  ProhibitUnusedVariable:
    enabled: yes
  ProhibitImplicitScopeVariable:
    enabled: yes
  ProhibitAbbreviationOption:
    enabled: yes
