---
- name: Comment out the sudo hint in /etc/bash.bashrc
  become: yes # noqa: yaml[truthy]
  lineinfile:
    path: /etc/bash.bashrc
    regex: '^(.*)(#.*to run a command as administrator.*)$'
    line: '#\1\2'
    backrefs: true
