---
dependencies:
  - role: add_repo
    vars:
      add_repo_filename: nodesource
      add_repo_key_url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      add_repo_name: NodeSource
      add_repo_urls:
        - deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main
        # - "deb-src https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main"
