#!/bin/bash

[[ $- == *i* ]] || return 0

# System
alias c='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias df='df -h'
alias h='history'
alias md='mkdir -p'
alias rd=rmdir

# XXX: Move to function or bin so we can accept multiple filenames
function vimwhich() { vim "$(command -v "$1")"; }

#-----------------------------------------------------------------------------
alias dumppath='echo -e ${PATH//:/\\n}'
alias dumpldpath='echo -e ${LD_LIBRARY_PATH//:/\\n}'
alias dotfiles='cd $DOTFILES'
alias dateh="echo;date --help | grep --color=never -E '^[[:space:]]+%'"

#-----------------------------------------------------------------------------
alias diffdir='diff -qr'

if command -v colordiff > /dev/null; then
  alias diff='colordiff'
  alias diffdir='colordiff -qr'
fi

#-----------------------------------------------------------------------------
# https://wiki.archlinux.org/index.php/Core_Utilities#grep
export GREP_COLOR="1;33"
alias grep='grep --color=auto'
alias g='grep --color=auto'
