#!/bin/bash

[[ $- == *i* ]] || return 0

# Start session in background if it doesn't already exist.

# XXX: Need to check if we are already in a tmux session and fail if so.
# XXX: Maybe alias ta needs to be a function instead

tmux_has_session() {
  tmux has-session -t "$USER" &> /dev/null \
    || tmux new-session -d -s "$USER"
}

# We want $USER to expand when defined, not when used.
# shellcheck disable=SC2139
alias ta="tmux_has_session ; tmux a -t $USER"

# swap this window to the left
alias swapl='tmux swap-window -t -1'

# swap this window to the right
alias swapr='tmux swap-window -t +1'

# swap this window with the one passed in
alias swapw='tmux swap-window -t'

# shellcheck disable=SC1003
function set_title() { printf '\ek%s\e\\' "$1"; }
export -f set_title

# shellcheck disable=SC1083
circled_digits=$(printf %s \${$'\xEA',\`,{a..s}} | iconv -f UTF-16BE)

tmux_winidx_circled() {
  local winidx
  winidx=$(tmux display-message -p '#I')

  if ((winidx > 20)); then
    echo "($winidx)"
  else
    echo "${circled_digits:winidx:1}"
  fi
}
