galaxy_info:
  author: your name
  description: Role to install binenv
  company: your company

  license: license type

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal

  galaxy_tags:
    - development
    - environment
