#!/usr/bin/env python

from vertexai.language_models import CodeChatSession

class ChatBot():
    def __init__(self):
        self._params()
        self.session = self._session()

    def _params(self, params={}):
        if params is None:
            session_params = {}

        params.setdefault('model', 'codechat-bison')

        self.params = params

    def _session(self, session_params=None):
        # Create a CodeChatSession with the given parameters
        if session_params is None:
            session_params = self.params
        return CodeChatSession(**session_params)

    def send_message(self, message):
        # Send the prompt to the CodeChatSession and get the response
        response = self.session.send(message)

        # Return the response as a string
        return response.text

if __name__ == '__main__':
    chatbot = ChatBot()

    while True:
        message = input("You: ")

        if message.lower() == 'quit':
            break

        response = chatbot.send_message(message)
        print("Bot:", response)
