---
- name: Gather facts
  package_facts:
    manager: auto

- name: Remove older Docker packages
  become: true
  apt:
    name: "{{ docker_remove_packages }}"
    state: absent
    purge: true
  when: "'docker-ce' not in ansible_facts.packages"

- name: Install Docker packages
  become: true
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
