---
- name: Remove older Docker packages
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: yes

# Install Docker packages from the Docker repository
- name: Install Docker packages
  include_role:
    name: install_pkgs
  vars:
    package_groups: "docker"
