---
# This must happen before the install packages task, so those are added here
# instead in the meta fold.

- name: Remove older Docker packages
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: yes

- include_role:
    name: install_pkgs
    vars:
      packages: "{{ docker_packages }}"
