---
- name: Remove older Docker packages
  become: true
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: true

- name: Install docker repo
  include_role:
    name: add_repo
    apply:
      vars:
        repo_list:
          - docker

- name: Install new packages
  include_role:
    name: install_pkgs
    apply:
      vars:
        packages: "{{ docker_packages }}"
