---
- name: Remove older Docker packages
  become: true
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: true

- name: Install Docker packages
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present

- name: Install new packages
  include_role:
    name: install_pkgs
    apply:
      vars:
        packages: "{{ docker_packages }}"
