---
- name: Remove older Docker packages
  become: true
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: true

# Include tasks to install Docker repository
- name: Install Repository Public Key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add APT repository for Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present


- name: Install Docker packages
  package:
    name: "{{ docker_packages }}"
    state: present
