#!/usr/bin/env python

import sys
print(sys.executable)

import jsonlines
import yaml

#-----------------------------------------------------------------------------
def load_yaml(filename):
    with open(filename, 'r') as yf:
        data = yaml.load(yf, Loader=yaml.FullLoader)

    return data

#-----------------------------------------------------------------------------
def save_jsonl(filename, data=[]):
    with jsonlines.open(filename, mode='w') as jf:
        jf.write_all(data)

#-----------------------------------------------------------------------------
def convert(yaml_file, jsonl_file):
    raw = load_yaml(yaml_file)
    objs = []

    for el in raw:
        for key, value in el.items():
            objs.append({"input_text":f"{key}", "output_text": f"{value}"})

    save_jsonl(jsonl_file, objs)

#-----------------------------------------------------------------------------
if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python mkjsonl <input_yaml_file> <output_jsonl_file>")
        sys.exit(1)

    yaml_file = sys.argv[1]
    jsonl_file = sys.argv[2]

    convert(yaml_file, jsonl_file)
