#!/usr/bin/env python

import sys
print(sys.executable)

import argparse
import jsonlines
import yaml

#-----------------------------------------------------------------------------
def load_yaml(filename):
    with open(filename, 'r') as yf:
        data = yaml.load(yf, Loader=yaml.FullLoader)

    return data

#-----------------------------------------------------------------------------
def save_jsonl(filename, data=[]):
    with jsonlines.open(filename, mode='w') as jf:
        jf.write_all(data)

#-----------------------------------------------------------------------------
def convert(yaml_file, jsonl_file):
    raw = load_yaml(yaml_file)
    objs = []

    for el in raw:
        for key, value in el.items():
            objs.append({"input_text":f"{key}", "output_text": f"{value}"})

    save_jsonl(jsonl_file, objs)

#-----------------------------------------------------------------------------
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Convert YAML to JSONL')
    parser.add_argument('input_yaml_file', type=str, help='The YAML file to convert')
    parser.add_argument('-o', '--output', dest='jsonl_file', type=str, required=True, help='The JSONL file to output')
    args = parser.parse_args()

    yaml_file = args.input_yaml_file
    jsonl_file = args.jsonl_file

    convert(yaml_file, jsonl_file)
