---
cli_pkgs_packages:
  - aptitude
  - build-essential
  - ca-certificates
  - colordiff
  - curl
  - dkms
  - dos2unix
  - elinks
  - expect
  - git
  - htop
  - jq
  - "linux-headers-{{ ansible_kernel }}"
  - markdown
  - mlocate
  - parallel
  - python3-pip
  - tmux
  - tree
  - unzip
  - vim
  - wget
  - xclip
  - zip
