---
- name: Setup work environment
  hosts: localhost

  vars:
    version_tracking_file: .version-tracking-file.yml

  roles:
    - role: version_tracking
    - role: common_pkgs
    - role: nerd_font
#    - role: nodejs
#    - role: pip_pkgs
    - role: docker
    - role: hashicorp
    - role: gcloud
    - role: vscode
    - role: misc_configuration

    - role: gnome_settings
      vars:
        gnome_settings_tilix_profile_filename: "{{ playbook_dir }}/harleypig-tilix-profile.dconf"

    - role: version_tracking
      vars:
        version_tracking_action: 'save'
